version: '3.9'

services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    image: node:22
    container_name: backend
    working_dir: /app
    volumes:
      - ./backend-nest:/app
    command: sh -c "corepack enable && pnpm install && pnpm start:dev"
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    image: node:22
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend-books:/app
    command: sh -c "corepack enable && pnpm install && pnpm dev --hostname 0.0.0.0"
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

  mongo-seed:
    image: node:22
    container_name: mongo-seed
    working_dir: /app
    volumes:
      - ./backend-nest:/app
    command: sh -c "corepack enable && pnpm install && pnpm exec ts-node mongo-seed/seed.ts"
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: "no"  
volumes:
  mongo-data:

networks:
  app-network: